### ISSUE TITLE
48182 illegal hardware instruction 

### ISSUE THREAD

**Issue by Air-Craft** [unsignedapps/swift-create-xcframework#28]
I just installed from the git clone and get this when I run `swift-create-xcframework --list-products`

Fatal error: file Xcodeproj/pbxproj.swift, line 400
[1]    48182 illegal hardware instruction  swift-create-xcframework --list-products

Xcode 12.2
MacOS 10.15.6

**Comment by bok-** [comment]
@Air-Craft Unfortunately SwiftPM's Xcode project generation does not support generating projects that include binary targets or system modules, which is what is happening at [Xcodeproj/pbxproj.swift:400](https://github.com/apple/swift-package-manager/blob/06d96d033ffdcbf97b741ed79d62127c4fe419b3/Sources/Xcodeproj/pbxproj.swift#L400). We've added some additional validation in version 1.3.1 to print out a more helpful error message instead of letting generation fail with a `fatalError()`
