### ISSUE TITLE
Create XCFramework with Bundle

### ISSUE THREAD

**Issue by rsarromatos** [unsignedapps/swift-create-xcframework#72]
Thanks for contributing to swift-create-xcframework!

When try to run `swift create-xcframework --platform ios --configuration release` in spm project that needs provide a Bundle, I receive the error:

```
/Users/usr/Documents/iosDesign/Sources/Design/Resources/Generated/DesignAssets.swift:182:19: error: type 'Bundle' has no member 'module'
    return Bundle.module
           ~~~~~~ ^~~~~~

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64 (in target 'Design' from project 'CoraDesign')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Design' from project 'Design')
(2 failures)
```

**swift-create-xcframework version:** `0.1.0` or the `master` branch, for example.
**Swift version:** 5.6.1
**Environment:** Xcode 13.4.1 / macOS Monterey 12.4

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/unsignedapps/swift-create-xcframework/issues)

**Comment by fedejordan** [comment]
I'm facing the same issue. 
When the swift packages are compiled in the main project, if your `Package.swift` definition contains resources, a file called `resource_bundle_accessor.swift` is created, which includes the following content:
```swift
import class Foundation.Bundle

private class BundleFinder {}

extension Foundation.Bundle {
    /// Returns the resource bundle associated with the current Swift module.
    static var module: Bundle = {
        let bundleName = "YourPackageName_YourPackageName"

        let candidates = [
            // Bundle should be present here when the package is linked into an App.
            Bundle.main.resourceURL,

            // Bundle should be present here when the package is linked into a framework.
            Bundle(for: BundleFinder.self).resourceURL,

            // For command-line tools.
            Bundle.main.bundleURL,
        ]

        for candidate in candidates {
            let bundlePath = candidate?.appendingPathComponent(bundleName + ".bundle")
            if let bundle = bundlePath.flatMap(Bundle.init(url:)) {
                return bundle
            }
        }
        fatalError("unable to find bundle named YourPackageName_YourPackageName")
    }()
}
```

The thing is that when the swift package Xcode project is created to generate the archive, via `swift-create-xcframework`, this file is not generated since there are no compilation of swift packages.

We need a new step in the Xcode project creation to generate such file (`resource_bundle_accessor.swift`) if the related `Package.swift` contains resources

More information:
- https://developer.apple.com/forums/thread/650158
- https://developer.apple.com/documentation/xcode/bundling-resources-with-a-swift-package
