### ISSUE TITLE
how to produce a static library in the xcframework?

### ISSUE THREAD

**Issue by ferologics** [unsignedapps/swift-create-xcframework#78]
what the title says. the tool always creates a dynamic framework even if the package library type is set to `.static`

**Comment by krin-san** [comment]
I found no way to do that because SPM project generator creates a Dynamic Framework target for any `.library` SPM Target. This bug is tracked since Jan 2018: https://github.com/apple/swift-package-manager/issues/4900, but the `generate-xcodeproj` command is already removed from SPM and Apple provided no alternative for it. This tool may break with Swift 5.8 release.

**Comment by ferologics** [comment]
oh, bummer. if it's of any help we used xcodebuild to create an xcframework from the package manifest.
